version: 2

project_name: treex

builds:
  - id: treex
    main: ./cmd/app
    binary: app
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - "README.md"
      - "LICENSE"
      - "completions/treex.bash"
      - "completions/_treex"
      - "completions/treex.fish"
      - "man/man1/*"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

# nFPM packages (deb, rpm, etc.)
# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: treex-deb
    package_name: treex
    formats:
      - deb
    builds:
      - treex
    vendor: "Arthur Debert"
    homepage: "https://github.com/arthur-debert/treex"
    maintainer: "Arthur Debert <arthur-debert@users.noreply.github.com>"
    description: "A CLI file viewer for annotated file trees."
    license: "MIT"
    contents:
      - src: ./man/man1/treex.1
        dst: /usr/share/man/man1/treex.1.gz
        packager: deb
        file_info:
          mode: 0644
      - src: ./completions/treex.bash
        dst: /usr/share/bash-completion/completions/treex
        file_info:
          mode: 0644
      - src: ./completions/_treex
        dst: /usr/share/zsh/site-functions/_treex
        file_info:
          mode: 0644
      - src: ./completions/treex.fish
        dst: /usr/share/fish/vendor_completions.d/treex.fish
        file_info:
          mode: 0644

env:
  - PKG_NAME={{ .Env.PKG_NAME }}
