name: Setup Python with Poetry
description: "Set up Python with Poetry"
inputs:
  python-version:
    description: "The Python version to use"
    required: false
    default: "3.x"
  cache-key-prefix:
    description: "An optional prefix for the cache key"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Poetry tool
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: ${{ runner.tool_cache }}/poetry
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-poetry-

    - name: Install Poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Set virtual environment path
      id: venv-path
      shell: bash
      env:
        VENV: .venv/bin/activate
      run: |
        echo "venv-path=.venv" >> "$GITHUB_OUTPUT"
        echo "venv-activate=.venv/bin/activate" >> "$GITHUB_OUTPUT"

    - name: Cache virtual environment
      id: cache-venv
      uses: actions/cache@v3
      if: steps.venv-path.outputs.venv-path != ''
      with:
        path: .venv
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-venv-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-venv-${{ inputs.python-version }}-

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry config virtualenvs.in-project true
        poetry install --no-interaction --with dev

    - name: Sanity check
      shell: bash
      run: poetry check
