name: Commit Homebrew Formula

on:
  workflow_run:
    workflows: ["Generate Homebrew Formula"]
    types:
      - completed

jobs:
    commit-formula:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: List Artifacts
              run: |
                curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts

            - name: Download Brew Formula
              uses: actions/download-artifact@v4
              with:
                name: brew-formula
                run-id: ${{ github.event.workflow_run.id }}

            - name: Clone Homebrew Tap Repository
              run: git clone https://github.com/arthur-debert/homebrew-tools.git /tmp/homebrew-tools


            - name: Copy Homebrew Formula
              run: cp /tmp/Formula/dotcat.rb /tmp/homebrew-tools/Formula/dotcat.rb

            - name: Commit and Push Changes
              working-directory: /tmp/homebrew-tools
              env:
                GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}  # Use the PAT instead of GITHUB_TOKEN
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git remote set-url origin https://x-access-token:${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}@github.com/arthur-debert/homebrew-tools.git
                git add Formula/dotcat.rb
                git commit -m "chore(homebrew): Update dotcat formula to ${{ github.event.inputs.tag_name || github.event.release.tag_name }}"
                git push origin main
