name: Update Homebrew Formula

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true

jobs:
  update-brew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Library Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Choose a suitable Python version

      # If you have steps to generate the formula, include them here.
      # For example, if you're using a script:
      # - name: Generate Homebrew Formula
      #   run: python generate_formula.py

      - name: Create Formula Directory
        run: mkdir -p Formula

      - name: Copy Homebrew Formula
        run: cp homebrew/dotcat.rb Formula/dotcat.rb

      - name: Create Pull Request to Homebrew Tap
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this secret is set in your repository settings.
          commit-message: "chore(homebrew): Update dotcat formula"
          title: "chore(homebrew): Update dotcat formula to ${{ github.event.inputs.tag_name || github.event.release.tag_name }}"
          branch: "update-dotcat-${{ github.event.inputs.tag_name || github.event.release.tag_name }}" # Dynamic branch name
          delete-branch: true # Automatically delete the branch after merging
          body: |
            Update dotcat formula to version ${{ github.event.inputs.tag_name || github.event.release.tag_name }}

            Generated by GitHub Actions.
          add-paths: Formula/dotcat.rb # Specify the file to be included in the pull request
          base: main # Ensure this is the correct base branch for your tap repository

