name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to PyPI'
        required: true
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-poetry # Reference your composite action
        with:
          python-version: '3.9' # Specify the Python version you want to use
          cache-key-prefix: 'test-env'

      - name: Build and Publish
        id: publish
        if: github.event.inputs.publish == 'true'
        run: |
          # Extract version from pyproject.toml using Poetry
          VERSION=$(poetry version -s)
          echo "release_version=$VERSION" >> $GITHUB_OUTPUT

          # Run publish script
          ./bin/publish

          # Create annotation with release link
          echo "::notice title=PyPI Release::Package published to https://pypi.org/project/dotcat/$VERSION/"
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_NON_INTERACTIVE: 1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ steps.publish.outputs.release_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          prerelease: true
