name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Tag name for the release'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-poetry # Reference your composite action
        with:
          python-version: '3.9' # Specify the Python version you want to use
          cache-key-prefix: 'test-env'

      - name: Update version
        shell: bash
        run: |
          poetry version ${{ github.event.inputs.release_version }}

      - name: Commit version
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/arthur-debert/dotcat.git
          git add pyproject.toml
          git commit -m "chore: Update version to ${{ github.event.inputs.release_version }}"
          git push origin main

      - name: Build
        shell: bash
        run: |
          poetry build

      - name: Publish
        shell: bash
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload --repository pypi dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ github.event.inputs.release_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true