name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v0.9.6)"
        required: true
        default: ""

permissions:
  contents: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: "3.11"
          cache-key-prefix: "brew-env"

      - name: Ensure HomebrewFormula directory exists
        run: mkdir -p HomebrewFormula

      - name: Install additional dependencies
        run: |
          source .venv/bin/activate
          pip install tomli

      - name: Run brew-update script with commit flag
        run: |
          source .venv/bin/activate
          chmod +x bin/brew-update
          ./bin/brew-update --commit

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git push
          else
            echo "No changes to push."
          fi
