name: Generate Homebrew Formula

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true

jobs:
  update-formula:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: '3.9'
          cache-key-prefix: 'test-env'

      - name: Set TAP_REPOSITORY variable
        id: set-tap-repository
        run: |
          echo "TAP_REPOSITORY=$GITHUB_REPOSITORY_OWNER/homebrew-tools" >> $GITHUB_ENV

      - name: Clone Homebrew Tap Repository
        env:
          TAP_REPOSITORY: ${{ env.TAP_REPOSITORY }}
        run: git clone https://github.com/${{ env.TAP_REPOSITORY }} /tmp/tap

      - name: Generate Brew Formula
        env:
          PYTHON_PATH: ${{ env.PYTHON_PATH }}
          TAP_REPOSITORY: ${{ env.TAP_REPOSITORY }}
        run: |
         ./bin/brew::update > /tmp/tap/Formula/$(basename ${{ github.repository }}).rb

      - name: Commit and Push Changes
        working-directory: /tmp/tap
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          TAP_REPOSITORY: ${{ env.TAP_REPOSITORY }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}@github.com/${{ env.TAP_REPOSITORY }}
          git add Formula/${{ github.repository }}.rb
          git commit -m "chore(homebrew): Update ${{ github.repository }} formula to ${{ github.event.inputs.tag_name || github.event.release.tag_name }}"
          git push origin main
